import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import { AGENT_IDS, emitGemini, parseArgv } from "./emit-gemini.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const script = path.join(here, "emit-gemini.mjs");

const tmpDirs: string[] = [];
afterEach(() => {
  for (const d of tmpDirs.splice(0)) {
    fs.rmSync(d, { recursive: true, force: true });
  }
});

function tmpDir(prefix: string) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  tmpDirs.push(dir);
  return dir;
}

const models: Record<string, string> = {
  orchestrator: "gemini-2.5-flash",
  grunt: "gemini-2.5-flash",
  implementer: "gemini-2.5-pro",
  thinker: "gemini-2.5-pro",
};

function writeSsot(ws: string) {
  const dir = path.join(ws, ".rulesync/subagents");
  fs.mkdirSync(dir, { recursive: true });
  for (const id of AGENT_IDS) {
    fs.writeFileSync(
      path.join(dir, `${id}.md`),
      `---
name: ${id}
description: "Agent ${id}: role."
targets:
  - claudecode
antigravity-cli:
  model: flash
geminicli:
  model: ${models[id]}
---
Body for ${id}.
`,
    );
  }
}

describe("parseArgv", () => {
  it("defaults and --check", () => {
    expect(parseArgv([])).toEqual({ ok: true, check: false });
    expect(parseArgv(["--check"])).toEqual({ ok: true, check: true });
    expect(parseArgv(["--wat"]).ok).toBe(false);
  });
});

describe("emitGemini", () => {
  it("does not delete pre-existing .gemini/orphan.txt", () => {
    const ws = tmpDir("emit-gemini-orphan-");
    writeSsot(ws);
    fs.mkdirSync(path.join(ws, ".gemini"), { recursive: true });
    fs.writeFileSync(path.join(ws, ".gemini/orphan.txt"), "keep\n");
    const r = emitGemini({ workspaceRoot: ws, check: false });
    expect(r.ok).toBe(true);
    expect(fs.readFileSync(path.join(ws, ".gemini/orphan.txt"), "utf8")).toBe("keep\n");
  });

  it("does not write $HOME/.gemini or os.homedir()/.gemini", () => {
    const ws = tmpDir("emit-gemini-ws-");
    const home = tmpDir("emit-gemini-home-");
    writeSsot(ws);
    const homeMarker = path.join(os.homedir(), ".gemini", "agents", "orchestrator", "agent.md");
    const beforeHome = fs.existsSync(homeMarker) ? fs.readFileSync(homeMarker, "utf8") : null;
    const prevHome = process.env.HOME;
    process.env.HOME = home;
    try {
      const r = emitGemini({ workspaceRoot: ws, check: false });
      expect(r.ok).toBe(true);
    } finally {
      if (prevHome === undefined) delete process.env.HOME;
      else process.env.HOME = prevHome;
    }
    expect(fs.existsSync(path.join(home, ".gemini"))).toBe(false);
    const afterHome = fs.existsSync(homeMarker) ? fs.readFileSync(homeMarker, "utf8") : null;
    expect(afterHome).toBe(beforeHome);
    expect(fs.readFileSync(path.join(ws, "GEMINI.md"), "utf8")).toBe("@AGENTS.md\n");
  });

  it("writes GEMINI.md pointer and nested agent.md FM only", () => {
    const ws = tmpDir("emit-gemini-write-");
    writeSsot(ws);
    const r = emitGemini({ workspaceRoot: ws, check: false });
    expect(r.ok).toBe(true);
    expect(fs.readFileSync(path.join(ws, "GEMINI.md"), "utf8")).toBe("@AGENTS.md\n");
    for (const id of AGENT_IDS) {
      const text = fs.readFileSync(path.join(ws, ".gemini/agents", id, "agent.md"), "utf8");
      expect(text).not.toMatch(/auto-generated|Generated by/i);
      expect(text.startsWith("---\n")).toBe(true);
      const close = text.indexOf("\n---\n");
      const fm = text.slice(4, close);
      const body = text.slice(close + 5);
      expect(fm).toBe(
        `name: ${id}\ndescription: "Agent ${id}: role."\nmodel: ${models[id]}`,
      );
      expect(body).toBe(`Body for ${id}.\n`);
    }
    expect(emitGemini({ workspaceRoot: ws, check: true }).ok).toBe(true);
  });

  it("fails check and write on flat agents/{id}.md; does not delete it", () => {
    const ws = tmpDir("emit-gemini-collide-");
    writeSsot(ws);
    const flat = path.join(ws, ".gemini/agents/orchestrator.md");
    fs.mkdirSync(path.dirname(flat), { recursive: true });
    fs.writeFileSync(flat, "flat-collision\n");
    const checked = emitGemini({ workspaceRoot: ws, check: true });
    expect(checked.ok).toBe(false);
    expect(String(checked.error)).toMatch(/collision/);
    expect(fs.readFileSync(flat, "utf8")).toBe("flat-collision\n");
    const wrote = emitGemini({ workspaceRoot: ws, check: false });
    expect(wrote.ok).toBe(false);
    expect(String(wrote.error)).toMatch(/collision/);
    expect(fs.readFileSync(flat, "utf8")).toBe("flat-collision\n");
    expect(fs.existsSync(path.join(ws, ".gemini/agents/orchestrator/agent.md"))).toBe(false);
    expect(fs.existsSync(path.join(ws, "GEMINI.md"))).toBe(false);
  });

  it("does not rewrite .gemini/settings.json; check ignores extras except collision", () => {
    const ws = tmpDir("emit-gemini-noprune-");
    writeSsot(ws);
    fs.mkdirSync(path.join(ws, ".gemini"), { recursive: true });
    const settings = path.join(ws, ".gemini/settings.json");
    fs.writeFileSync(settings, '{"keep":true}\n');
    fs.writeFileSync(path.join(ws, ".gemini/extra.txt"), "stay\n");
    expect(emitGemini({ workspaceRoot: ws, check: false }).ok).toBe(true);
    expect(fs.readFileSync(settings, "utf8")).toBe('{"keep":true}\n');
    expect(fs.readFileSync(path.join(ws, ".gemini/extra.txt"), "utf8")).toBe("stay\n");
    expect(emitGemini({ workspaceRoot: ws, check: true }).ok).toBe(true);
  });
});

describe("cli", () => {
  it("unknown flag → stderr + exit 1", () => {
    const cli = spawnSync(process.execPath, [script, "--wat"], {
      encoding: "utf8",
      timeout: 20_000,
    });
    expect(cli.status).toBe(1);
    expect(cli.stderr).toMatch(/unknown flag/);
  });
});
