import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import { parse as parseToml } from "smol-toml";
import {
  emitMcpPolicy,
  loadPolicy,
  parseArgv,
  requiredDeepMatch,
  stripJsonc,
  validatePolicy,
} from "./emit-mcp-policy.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");
const script = path.join(here, "emit-mcp-policy.mjs");

const tmpDirs: string[] = [];
afterEach(() => {
  for (const d of tmpDirs.splice(0)) {
    fs.rmSync(d, { recursive: true, force: true });
  }
});

function tmpDir(prefix: string) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  tmpDirs.push(dir);
  return dir;
}

const basePolicy = {
  default: "deny" as const,
  allow: [] as string[],
  plugins: { denyDefault: true },
  servers: {} as Record<string, unknown>,
  agents: {
    orchestrator: { inherit: false },
    implementer: { inherit: false },
    thinker: { inherit: false },
    grunt: { inherit: false },
  },
};

function writePolicy(ws: string, policy: unknown) {
  const dir = path.join(ws, ".rulesync");
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(
    path.join(dir, "mcp-policy.jsonc"),
    `// fixture\n${JSON.stringify(policy, null, 2)}\n`,
  );
}

function seedHostStubs(ws: string) {
  fs.mkdirSync(path.join(ws, ".claude"), { recursive: true });
  fs.writeFileSync(
    path.join(ws, ".claude/settings.json"),
    JSON.stringify(
      {
        permissions: { deny: ["Agent(Explore)", "Agent(Plan)", "Agent(general-purpose)"] },
        hooks: { PreToolUse: [{ matcher: "Agent" }] },
      },
      null,
      2,
    ) + "\n",
  );
  fs.mkdirSync(path.join(ws, ".codex"), { recursive: true });
  fs.writeFileSync(path.join(ws, ".codex/config.toml"), "[agents]\nmax_depth = 1\n");
}

describe("parseArgv", () => {
  it("defaults and --check", () => {
    expect(parseArgv([])).toEqual({ ok: true, check: false });
    expect(parseArgv(["--check"])).toEqual({ ok: true, check: true });
    expect(parseArgv(["--wat"]).ok).toBe(false);
  });
});

describe("validatePolicy", () => {
  it("rejects default !== deny and non-array allow", () => {
    expect(validatePolicy({ ...basePolicy, default: "allow" }).ok).toBe(false);
    expect(validatePolicy({ ...basePolicy, allow: "x" }).ok).toBe(false);
  });

  it("rejects allow names missing from non-empty servers", () => {
    expect(
      validatePolicy({
        ...basePolicy,
        allow: ["foo"],
        servers: { bar: { command: "x" } },
      }).ok,
    ).toBe(false);
    expect(
      validatePolicy({
        ...basePolicy,
        allow: ["foo"],
        servers: { foo: { command: "x" } },
      }).ok,
    ).toBe(true);
  });
});

describe("emitMcpPolicy", () => {
  it("deny-all emit on tmp workspaceRoot", () => {
    const ws = tmpDir("emit-mcp-deny-");
    const home = tmpDir("emit-mcp-home-");
    fs.mkdirSync(path.join(home, ".grok"), { recursive: true });
    const homeCfg = path.join(home, ".grok/config.toml");
    fs.writeFileSync(homeCfg, "keep = true\n");
    writePolicy(ws, basePolicy);
    seedHostStubs(ws);
    const r = emitMcpPolicy({ workspaceRoot: ws, check: false });
    expect(r.ok).toBe(true);
    expect(fs.readFileSync(homeCfg, "utf8")).toBe("keep = true\n");

    const mcp = JSON.parse(fs.readFileSync(path.join(ws, ".mcp.json"), "utf8"));
    expect(mcp).toEqual({ mcpServers: {} });
    const agents = JSON.parse(fs.readFileSync(path.join(ws, ".agents/mcp_config.json"), "utf8"));
    expect(agents).toEqual({ mcpServers: {} });

    const grokRaw = fs.readFileSync(path.join(ws, ".grok/config.toml"), "utf8");
    expect(grokRaw.startsWith("# Generated by emit-mcp-policy.mjs")).toBe(true);
    expect(grokRaw).not.toMatch(/\[features\]/);
    expect(grokRaw).not.toMatch(/\[\[permissions\]\]/);
    expect(grokRaw).not.toMatch(/deny_default/);
    expect(grokRaw).not.toMatch(/\[mcp\.servers/);
    const grok = parseToml(grokRaw) as {
      plugins?: { enabled?: unknown[]; deny_default?: boolean };
      permission?: { deny?: string[]; allow?: string[] };
      permissions?: unknown;
      mcp?: unknown;
      mcp_servers?: unknown;
    };
    expect(grok.plugins?.enabled).toEqual([]);
    expect(grok.plugins?.deny_default).toBeUndefined();
    expect(grok.mcp).toBeUndefined();
    expect(grok.mcp_servers).toBeUndefined();
    expect(grok.permissions).toBeUndefined();
    expect(grok.permission?.deny).toContain("MCPTool");
    expect(grok.permission?.allow ?? []).toEqual([]);

    const claude = JSON.parse(fs.readFileSync(path.join(ws, ".claude/settings.json"), "utf8"));
    expect(claude.enableAllProjectMcpServers).toBe(false);
    expect(claude.enabledMcpjsonServers).toEqual([]);
    expect(claude.permissions.deny).toContain("mcp__*");
    expect(claude.permissions.deny).toContain("Agent(Explore)");
    expect(claude.permissions.deny).toContain("Agent(orchestrator)");
    expect(claude.permissions.deny).toContain("Agent(Plan)");
    expect(claude.hooks).toBeTruthy();

    const codex = parseToml(fs.readFileSync(path.join(ws, ".codex/config.toml"), "utf8")) as {
      agents?: { max_depth?: number };
      mcp_servers?: unknown;
    };
    expect(codex.agents?.max_depth).toBe(1);
    expect(codex.mcp_servers).toBeUndefined();
  });

  it("named-allow fixture emits only that server; leftover grok disabled", () => {
    const ws = tmpDir("emit-mcp-allow-");
    const policy = {
      ...basePolicy,
      allow: ["notes"],
      servers: {
        notes: { command: "npx", args: ["-y", "notes-mcp"] },
        extra: { command: "nope" },
      },
    };
    writePolicy(ws, policy);
    seedHostStubs(ws);
    fs.mkdirSync(path.join(ws, ".grok"), { recursive: true });
    fs.writeFileSync(
      path.join(ws, ".grok/config.toml"),
      "[mcp_servers.stale]\ncommand = \"old\"\nenabled = true\n",
    );
    fs.writeFileSync(
      path.join(ws, ".codex/config.toml"),
      "[agents]\nmax_depth = 1\n\n[mcp_servers.stale]\ncommand = \"old\"\n",
    );
    const r = emitMcpPolicy({ workspaceRoot: ws, check: false });
    expect(r.ok).toBe(true);

    const mcp = JSON.parse(fs.readFileSync(path.join(ws, ".mcp.json"), "utf8"));
    expect(Object.keys(mcp.mcpServers)).toEqual(["notes"]);
    expect(mcp.mcpServers.extra).toBeUndefined();
    const agents = JSON.parse(fs.readFileSync(path.join(ws, ".agents/mcp_config.json"), "utf8"));
    expect(Object.keys(agents.mcpServers)).toEqual(["notes"]);

    const grok = parseToml(fs.readFileSync(path.join(ws, ".grok/config.toml"), "utf8")) as {
      plugins?: { enabled?: unknown[] };
      permission?: { deny?: string[]; allow?: string[] };
      mcp?: unknown;
      mcp_servers?: Record<string, { enabled?: boolean; command?: string }>;
    };
    expect(grok.plugins?.enabled).toEqual([]);
    expect(grok.permission?.deny).toContain("MCPTool");
    expect(grok.permission?.allow).toContain("MCPTool(notes__*)");
    expect(grok.mcp).toBeUndefined();
    expect(grok.mcp_servers?.stale?.enabled).toBe(false);
    expect(grok.mcp_servers?.stale?.command).toBe("old");
    expect(grok.mcp_servers?.notes?.command).toBe("npx");

    const claude = JSON.parse(fs.readFileSync(path.join(ws, ".claude/settings.json"), "utf8"));
    expect(claude.enabledMcpjsonServers).toEqual(["notes"]);

    const codex = parseToml(fs.readFileSync(path.join(ws, ".codex/config.toml"), "utf8")) as {
      mcp_servers?: Record<string, unknown>;
    };
    expect(Object.keys(codex.mcp_servers || {})).toEqual(["notes"]);
    expect(codex.mcp_servers?.stale).toBeUndefined();
  });

  it("--check fails on drift then passes; writes nothing on check", () => {
    const ws = tmpDir("emit-mcp-check-");
    writePolicy(ws, basePolicy);
    seedHostStubs(ws);
    expect(emitMcpPolicy({ workspaceRoot: ws, check: false }).ok).toBe(true);
    expect(emitMcpPolicy({ workspaceRoot: ws, check: true }).ok).toBe(true);

    const mcpPath = path.join(ws, ".mcp.json");
    const before = fs.readFileSync(mcpPath, "utf8");
    fs.writeFileSync(mcpPath, JSON.stringify({ mcpServers: { leaked: {} } }, null, 2) + "\n");
    const drifted = emitMcpPolicy({ workspaceRoot: ws, check: true });
    expect(drifted.ok).toBe(false);
    expect(String(drifted.error)).toMatch(/drift/);
    expect(fs.readFileSync(mcpPath, "utf8")).not.toBe(before);

    fs.writeFileSync(mcpPath, before);
    expect(emitMcpPolicy({ workspaceRoot: ws, check: true }).ok).toBe(true);

    const cli = spawnSync(process.execPath, [script, "--check"], {
      encoding: "utf8",
      cwd: ws,
      timeout: 20_000,
    });
    expect(cli.status).toBe(0);
  });
});

describe("repo SSOT", () => {
  it("allow is empty and not cloudflare/docker", () => {
    const policy = loadPolicy(repoRoot);
    expect(validatePolicy(policy).ok).toBe(true);
    expect(policy.allow).toEqual([]);
    const names = policy.allow.map((n: string) => n.toLowerCase());
    expect(names).not.toContain("cloudflare");
    expect(names).not.toContain("docker");
    expect(stripJsonc(fs.readFileSync(path.join(repoRoot, ".rulesync/mcp-policy.jsonc"), "utf8"))).toMatch(
      /"default"\s*:\s*"deny"/,
    );
  });

  it("skipKeyPattern still matches mcp(servers)?", () => {
    const manifest = JSON.parse(
      fs.readFileSync(path.join(repoRoot, ".rulesync/global-settings/manifest.json"), "utf8"),
    );
    expect(manifest.skipKeyPattern).toMatch(/mcp\(servers\)\?/);
    const re = new RegExp(manifest.skipKeyPattern, "i");
    expect(re.test("mcp")).toBe(true);
    expect(re.test("mcpServers")).toBe(true);
  });

  it("subagent inherit flags stay none/false", () => {
    const dir = path.join(repoRoot, ".rulesync/subagents");
    for (const name of fs.readdirSync(dir).filter((f) => f.endsWith(".md"))) {
      const text = fs.readFileSync(path.join(dir, name), "utf8");
      if (text.includes("grokcli:")) {
        expect(text).toMatch(/mcpInheritance:\s*none/);
      }
      if (text.includes("antigravity-cli:")) {
        expect(text).toMatch(/inheritMcp:\s*false/);
      }
    }
  });
});

describe("requiredDeepMatch", () => {
  it("allows extra disk keys", () => {
    expect(requiredDeepMatch({ a: 1, extra: true }, { a: 1 })).toBe(true);
    expect(requiredDeepMatch({ a: 2 }, { a: 1 })).toBe(false);
  });
});
